### ISSUE TITLE
cleanup() doesn't always run

### ISSUE THREAD

**Issue by coclav** [FWeinb/electron-screenshot-app#1]
Hi, 

I can't really reproduce this bug but happens often enough for me to mention here. 

The `cleanup()` function doesn't seem to be fired all the time. line 124. which result in windows opened in the background and impossible to close. 

what i have done is calling the callback in my own callback

````
screenshot({
  url: 'file://blabla' + ,
  width: res.width,
  height: res.height,
  page:true
},
function(err, image, cleanup) {
  // ...
  cleanup();
}, 1000)
```
but not sure this is very sustainable...

**Comment by FWeinb** [comment]
We have to resort to calling the `cleanup()` function after processing the buffer. if the window is freed so is the buffer holding the image data.
